version: "3.8"

services:
  api_sala:
    build: .
    ports:
      - "6000:6000"
    #volumes:
      #- ./banco.db:/app/banco.db  # Mapeia o banco fora do container, opcional
    networks:
      - projeto-apis

networks:
  projeto-apis:
    external: true